class initialize:
    def __init__(self) -> None:
        self.movies = [
            "Doctor Strange",
            "Spiderman",
            "Avatar",
            "Lord of the rings",
            "Doraemon",
            "Transformers",
            "Wakanda",
            "Shin Chan",
            "Spongebob",
            "mario",
            "Batman",
            "James Bond",
            "Aspalela - Duyung",
            "Ultraman",
            "Power Rangers",
            "Star wars",
            "Thor",
            "Captain America",
            "John Wick",
            "Rush Hour",
            "Superman",
            "ghost rider",
            "twilight",
            "Robotcop",
            "Tomb Raider",
            "Frozen",
            "Cindrella",
            "The Matrix",
            "Zombie",
            "Lion King",
        ]

        self.action = [
            "monkey climbing a tree",
            "kangaroo boxing",
            "alligator washing a car",
            "bird building a nest",
            "dog driving a car",
            "an elephant cooking",
            "giraffe playing football",
            "chicken dancing",
            "penguin driving motor",
            "pig playing golf",
            "cat giving himself a bath",
            "bear calling his girlfriend",
            "dinosaur having ice-cream",
            "panda giving birth",
            "frog playing basketball",
            "snake skateboarding",
            "Fish Jogging",
            "tiger sweeping floor",
            "praying mantis lifting dumbell ",
            "monkey playing bowling",
            "gorilla ngajat",
            "dolphin playing badminton",
            "giraffe turn into kingkong",
            "whale reading book",
            "penguin knitting cloth",
        ]